### ISSUE TITLE
Retain MQTT Hass message

### ISSUE THREAD

**Issue by towerhand** [OpenZWave/Zwave2Mqtt#122]
Not sure if this is a bug or not, but In the MQTT settings I activated the retain option. I'm using MQTT Explorer to verify all messages and I can see the retain flag on the messages sent to the main prefix (zwave2mqtt in my case) but the ones sent to for hass discovery (homeassistant prefix) are not getting the retain flag. I noticed Tasmota, espixelsitck and zigbee2mqtt add the retain flag to the messages sent for hass if the retain option is on. I had a couple lights disappear from hass a couple days ago and they came back when I restarted zwave2mqtt so maybe this have something to do with that.

**Comment by robertsLando** [comment]
@tomerhand The retain flag is not set on discovery messages because if you remove a device you cannot remove it anyway (you should manually delete it from broker retained messages by sending a message with empty payload to the broker to the discovery topic). To prevent this, as described in docs [here](https://github.com/OpenZWave/Zwave2Mqtt#robot-home-assistant-integration-beta) I have added birth and will message to hass so I can detect when hass goes offline/online to resend discovery payloads:

```yaml
mqtt:
  discovery: true
  discovery_prefix: <your_discovery_prefix>
  broker: [YOUR MQTT BROKER]  # Remove if you want to use builtin-in MQTT broker
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline' 
```
