### ISSUE TITLE
[feat] Node events and scene events on hass discovery

### ISSUE THREAD

**Issue by sdwilsh** [OpenZWave/Zwave2Mqtt#187]
This might also be a feature request.  It's unclear because the documentation for group association is fairly minimal today.

I've followed [these instructions](https://community.home-assistant.io/t/ge-14294-and-jasco-equivilant-zwave-dimmer-double-tap-event-on-associaton-group-3-need-config-help/29469/17) to make the double-tap work for my GE 14294 dimmer switch.  I even see an event in mqtt (`zwave2mqtt/Office/3/event {"time":1577849592927,"value":255}`), so I know everything is working correctly on the zwave side all the way through mqtt.  I do not see any way to add it so that hass can auto-discover it, however.

**Comment by sdwilsh** [comment]
I think we'd want this to show up as a sensor per https://www.home-assistant.io/integrations/sensor.mqtt/

**Comment by robertsLando** [comment]
Which OZW version are you using?

**Comment by robertsLando** [comment]
If you are using OZW 1.6 you could manage events because they are associated to valueIDs, otherwise it needs some thoughts

**Comment by robertsLando** [comment]
What I can suggest you is to manually create the entity on hass side: https://www.home-assistant.io/docs/configuration/devices/

**Comment by sdwilsh** [comment]
Yeah, I can set it up myself, but I put the feature request in because it'd be nice to have it automatically there.  The GE 14294 is interesting because it has three different association groups, and all three have a different set of events, as far as I can tell.

It'd be nice if they were auto-populated as things for the device.  That would require two changes, I think:
1) OpenZwave would have to have both association groups set to auto (which I think is okay per their guidelines, but I should start a discussion thread about it)
2) The automatic population of "Home Assistant - Devices" section should look at associated groups as well

Another option would allowing the manual addition to "Home Assistant - Devices".

**Comment by sdwilsh** [comment]
I forgot to answer the OZW version question - I'm using whatever is part of the Docker install from the readme.  I'm not sure how to check what version that is, to be honest.

**Comment by sdwilsh** [comment]
> What I can suggest you is to manually create the entity on hass side: https://www.home-assistant.io/docs/configuration/devices/

This turns out to not work as well as one might hope.  As a concrete example, I want my blinds to go down if I double tap down on my light switch.  If I closed them with the double tap, but something else opens them, once I double tap down again, nothing happens because there was no change of state.  I thought about just listening for the mqtt topic as the trigger, but because I normally want my zwave status for devices retained, once home assistant starts and listens, it thinks there was a double tap when there was not one.

**Comment by sdwilsh** [comment]
Sharing this here since I was able to make it work by exposing each double-tap direction as a binary sensor in home assistant with this:

```
binary_sensor:
   - platform: mqtt
     name: 'Office LightRoom Off Double-Tap'
     state_topic: 'zwave2mqtt/Office/3/event'
     json_attributes_topic: 'zwave2mqtt/Office/3/event'
     json_attributes_template: '{{ value_json | tojson }}'
     value_template: '{{ value_json.value }}'
     payload_on: '0'
     expire_after: 1
   - platform: mqtt
     name: 'Office LightRoom On Double-Tap'
     state_topic: 'zwave2mqtt/Office/3/event'
     json_attributes_topic: 'zwave2mqtt/Office/3/event'
     json_attributes_template: '{{ value_json | tojson }}'
     value_template: '{{ value_json.value }}'
     payload_on: '255'
     expire_after: 1
```

Downside with this approach is that most of the time the sensor is unavailable (due to `expires_after`), but without that the state will never change.  Adding `json_attributes_template` (with `json_attributes_topic`) kept any automations from trigger on home assistant startup.
