### ISSUE TITLE
Battery powered sensors dead on restart

### ISSUE THREAD

**Issue by sarkyscouser** [OpenZWave/Zwave2Mqtt#284]
I've just tried to migrate my zwave setup to zwave2mqtt from home assistant's internal zwave ahead of any future breaking changes.

Whilst I've had things working with HA for over a year now, the same zwave controller and sensors aren't working with zwave2mqtt.  The controller is a ZME EU UZB1 and I have 4 door sensors which are detected as "Kaipule Technology Co. Ltd" IM20 sensors.   

I can get the sensors to be detected by zwave2mqtt initially and they report the correct battery level, but the open/closing of the doors isn't registered by zwave2mqtt or HA. 

After a while or on restart the sensors all become dead and that's that.

In HA via mosquitto MQTT, I have 8 sensors listed, some are node_IDX and some are the location/name specified in zwave2mqtt so there's some duplication going on.

I'm using docker for zwave2mqtt, mosquitto and HA, my docker compose is below.  The host is Arch (LTS kernel).

I have also posted my zwave2mqtt config below, assume awake is selected.

```yaml
version: "3"

services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - /mnt/btrfs_raid/docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mnt/btrfs_raid/docker/mosquitto/data:/mosquitto/data
      - /mnt/btrfs_raid/docker/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

  zwave2mqtt:
    container_name: zwave2mqtt
    image: robertslando/zwave2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    networks:
      - zwave
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - /mnt/btrfs_raid/docker/zwave2mqtt/store:/usr/src/app/store
    ports:
      - 8091:8091

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    volumes:
      - /mnt/btrfs_raid/docker/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/London
    dns:
      - 9.9.9.9
      - 1.1.1.1
    restart: always
    network_mode: host

  networks:
    zwave:
```

![ScreenClip](https://user-images.githubusercontent.com/1990152/75716417-0a57e080-5cc7-11ea-92f4-b71656c90c86.png)
![ScreenClip2](https://user-images.githubusercontent.com/1990152/75716423-0cba3a80-5cc7-11ea-9dce-42b965fe0e97.png)
