### ISSUE TITLE
How do I resolve an "Unknown" product? [question] 

### ISSUE THREAD

**Issue by djdd87** [OpenZWave/Zwave2Mqtt#427]
I added a Ring Extender, but the UI shows it as follows:

![image](https://user-images.githubusercontent.com/22151993/80909570-358b9a00-8d21-11ea-859f-1211603ec386.png)

Here's the product page: https://products.z-wavealliance.org/products/3686?selectedFrequencyId=1

I saw the docs say to enable "Auto Update Config File", but that option isn't in my Z-Wave settings.

So how do I get ZWave2Mqtt to recognise it?

Here's my docker-compose in case that's useful:

```
  zwave2mqtt:
    container_name: zwave2mqtt
    image: robertslando/zwave2mqtt:latest
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    networks:
      - zwave
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - /home/pi/docker/zwave2mqtt/store:/usr/src/app/store
    ports:
      - 8091:8091
```
