### ISSUE TITLE
[bug] GE Fans show up as light switches

### ISSUE THREAD

**Issue by jshridha** [OpenZWave/Zwave2Mqtt#51]
Build/Run method:
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.1
Openzwave Version: 1.4.1

**Describe the bug**
GE fans show up as lights in hass rather than fans (see image below):

![image](https://user-images.githubusercontent.com/11232787/61327783-b1931080-a7e7-11e9-9599-2db960f541ed.png)

The zwave protocol is using command class 38, which is supposed to be reserved for lights, so this likely needs to be fixed using a manual hard-coded approach. Maintaining a list of anomalies might be a good idea.

So far, I've seen this issue with the following device ids:
99-12340-18756
99-12593-18756

The configuration for the fans can be found here:
https://github.com/OpenZWave/open-zwave/blob/master/config/ge/12724-dimmer.xml

**Comment by robertsLando** [comment]
Thanks for the detailed issue @jshridha. To make this work I have created a file named `devices.js` inside home assistant folder that will contain all 'non conventional' devices configuration that zwave2mqtt can't recogize its own. Now I don't have any fun to test it but I ask you if it is possible to do the test your own this way:

Follow this guide https://github.com/OpenZWave/Zwave2Mqtt#components-management

As you can see you can manually edit the json file that I use to create the discovery topic/payload for the hass devices. I ask you if it is possible to find the correct fan configuration that allow you to control the fan from hass and then send it back to me here so I can add it to the device configurations. 

If you need help on how to create that configuration just ask me in slack channel :) 

Thanks!

**Comment by robertsLando** [comment]
I have find an interesting integration of a fun using command class 38 here: 
https://selfhostedhome.com/migrating-to-zwave2mqtt-for-home-assistant/

```yaml
name: "Office Fan"
    command_topic: "zwave2mqtt/3/38/1/0/set"
    speed_command_topic: "zwave2mqtt/3/38/1/0/set"
    speed_state_topic: "zwave2mqtt/3/38/1/0"
    state_topic: "zwave2mqtt/3/38/1/0"
    speeds: ["off", "low", "medium", "high"]
    payload_low_speed: 24
    payload_medium_speed: 50
    payload_high_speed: 99
    payload_off: 0
    payload_on: 99
    state_value_template: "{% if (value | int) == 0 %} 0 {% else %} 99 {% endif %}"
    speed_value_template: >-
      {% if (value | int) == 25 %}
        24
      {% elif (value | int) == 51 %}
        50
      {% elif (value | int) == 99 %}
        99
      {% else %}
        0
      {% endif %}
```

Starting from this it should be easily
