### ISSUE TITLE
GE/enbrighten switches[question] 

### ISSUE THREAD

**Issue by benchdog93** [OpenZWave/Zwave2Mqtt#804]
When adding name in control panel switches become disabled, remove the name in control panel and the are active again. Dimmer does not retain its position and needs multiple clicks. The way I would expect the dimmer to work would be a single click on, set brightness, a single click off, and for the brightness level to be maintained. At least that how they worked with past applications I have used.

Not sure how to fix this

I am using:
Z-Wave to MQTT
Current version: 0.8.1 (changelog)

Switches I am having an issue with:
14292 In-Wall Smart Toggle Switch (GE (Jasco Products))
14295 In-Wall Smart Toggle Dimmer (GE (Jasco Products))

Thank you for your help.

**Comment by robertsLando** [comment]
> When adding name in control panel switches become disabled

Sorry but I don't understand what you mean, are you speaking about home assistant switches or switches in z2m control panel?

**Comment by benchdog93** [comment]
I am talking about z2m control panel. I can rename them in HA fine but that does not show their name in the z2m control panel. I have the 14288 Duplex Receptacles (GE (Jasco Products)) that allow me to add a name in the z2m control panel and work as expected. I have several of these receptacles and switches to add and it would make it easier to manage having their name and location in the z2m control panel. 

Thank you

**Comment by robertsLando** [comment]
@benchdog93 Could you show me a gif that shows this ?

**Comment by benchdog93** [comment]
![z2m_control_panel](https://user-images.githubusercontent.com/51010158/96616311-6ad87400-12d0-11eb-8e64-3314a52e21d9.GIF)

Attached is the screen shot of my z2m control panel. I think this is what you are asking for.

**Comment by benchdog93** [comment]
![mqtt](https://user-images.githubusercontent.com/51010158/96616933-f5b96e80-12d0-11eb-8592-7b943a254d91.GIF)

This is what it looks like in mqtt

**Comment by benchdog93** [comment]
![devive_in_mqtt](https://user-images.githubusercontent.com/51010158/96618668-3b773680-12d3-11eb-8db4-f1e21ed6def6.GIF)

This is where I rename it for HA

**Comment by robertsLando** [comment]
@benchdog93 When you rename it it looses the reference in zwave2mqtt, you should rename it on zwave2mqtt

**Comment by benchdog93** [comment]
This is my issue. When I rename swithes, I've listed above, in zwave2mqtt I can not operate the switch in Home Assistant, When clicking on the switches to change state it changes for an instant then returns back and no longer operates. It is the same with both types of switches listed. Also when I remove the name in zwave2mqtt the switches operate in HA. I can rename these switches in mqtt but this only changes their name in HA. I need them to be renamed in zwave2mqtt to manage my network and to work as expected.

Also, when the dimmer switch is functional (not renamed in zwave2mqtt) it does not work as expected. Dimmer does not retain its position (brightness level) and needs multiple clicks. The way I would expect the dimmer to work would be a single click on, set brightness, a single click off, and for the brightness level to be maintained. At least that how they worked with past applications I have used. The way it operates now is click on set the level for brightness then the first click turns off the light and a second click is required to return the switch to the off state in HA.

New to this and maybe I am doing sonething wrong but when I installed the receptacle and renamed in zwave2mqtt all worked fine. 

Let me know if you need more.

Thank you

![z2m rename](https://user-images.githubusercontent.com/51010158/96722631-96646880-137b-11eb-8936-8e9bebc91c8b.GIF)

**Comment by robertsLando** [comment]
@benchdog93 After renaming themyou hae to press on `Rediscover node` because the name is part of the topic

**Comment by robertsLando** [comment]
Also you should enable retain in mqtt settings

**Comment by benchdog93** [comment]
I am away until Monday and see if these changes work.

Thank you

**Comment by benchdog93** [comment]
I was able to work on it tonight. Does not work still. I had already tried Rediscover Node in the past.

**Comment by robertsLando** [comment]
Could you show me your settings?

**Comment by benchdog93** [comment]
Screen shots of my settings

![zwave](https://user-images.githubusercontent.com/51010158/97022195-d49b8c80-1521-11eb-9e26-309c5628b820.GIF)
![mqtt](https://user-images.githubusercontent.com/51010158/97022230-dc5b3100-1521-11eb-86d2-7ae71788ba42.GIF)
![gateway](https://user-images.githubusercontent.com/51010158/97022261-e4b36c00-1521-11eb-99eb-40dd02ce8663.GIF)

**Comment by robertsLando** [comment]
@benchdog93 From a settings side everything seems good. As I can see you are using node names in nodes so when you chage them also topics of that node will change and you will need to rediscover that specific node to update discovery tepmplates with updated topics. I think there should be  a user error somewhere in the process because I cannot see anythign wrong here

**Comment by benchdog93** [comment]
I will need to figure it out I don't see any user errors. When I have a day to dedicate to it I will and let you know.

Did you look at the dimmer switch issue I am seeing? I have not look at that for a while.

**Comment by robertsLando** [comment]
Yes I looked at it but can't figure out what's wrong there, I'm sorry :( let me know if you find something that I can help

**Comment by teknomar7** [comment]
I was never able to get my GE dimmer / motion sensor switches to work with the default configuration in zwave2mqtt.  The regular switches work fine, but for dimmer / motion I had to disable auto discovery in zwave2mqtt for those and define them manually in the HA config file.  This is what my configuration looks like for a dimmer...

```
light:
  - platform: mqtt
    name: "Dining Room Table"
    command_topic: "zwave2mqtt/DiningRoom/Table/38/1/0/set"
    # state_topic: "zwave2mqtt/LivingRoom/DimmerPlug/38/1/0"
    # state_value_template: "{{ \"off\" if value_json.value == 0 else \"on\" }}"
    brightness_command_topic: "zwave2mqtt/DiningRoom/Table/38/1/0/set"
    brightness_scale: '99'
    brightness_state_topic: "zwave2mqtt/DiningRoom/Table/38/1/0"
    brightness_value_template: "{{ value_json['value'] }}"
    on_command_type: "brightness"
    payload_on: 99
    payload_off: 0
    device:
      identifiers:
        - zwave2mqtt_0xdfa4123a_node6
      manufacturer: GE (Jasco Products)
      model: 46203 In-Wall Smart Dimmer (0x3235)
      name: DiningRoom-Table
      sw_version: Unknown
    unique_id: zwave2mqtt_0xdfa4123a_6-38-1-0
```
